spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:org.mariadb.jdbc.Driver}
    url: jdbc:${RDB_TYPE:mariadb}://${RDB_HOST:localhost}:${RDB_PORT:3306}/${RDB_SCHEMA:gwangsan_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
  jpa:
    hibernate:
      dialect: ${DB_DIALECT:org.hibernate.dialect.MariaDBDialect}
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET:qXWbwKO97FDyg8AdNGh5SakyMHgdEdyfUZi3WPxKZ/c=}
  refreshSecret: ${JWT_REFRESH_SECRET:bddf2bea2033a184add4770ca6fe8957de4e175f2a295658d3dca73a458573c6}
