name: CD

on:
  push:
    branches: [ "develop", "main" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: gwangsan-githubaction
  CODE_DEPLOY_APPLICATION_NAME: gwangsan-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: gwangsan-dg

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download firebase-service-account.json from S3
        run: |
          mkdir -p src/main/resources
          aws s3 cp s3://gwangsan-githubaction/firebase-service-account.json src/main/resources/firebase-service-account.json

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew build --no-daemon -x test





      - name: Build Docker image and save as tar
        run: |
          docker build -t gwangsan-app .
          mkdir -p output/docker-image
          docker save gwangsan-app > output/docker-image/gwangsan-app.tar

      - name: Prepare appspec.yml and scripts
        run: |
          mkdir -p output/scripts
          cp appspec.yml output/
          cp -r scripts/* output/scripts/

      - name: Zip output directory
        run: |
          cd output
          zip -r ../deploy-package.zip appspec.yml scripts docker-image

      - name: Upload to AWS S3
        run: |
          aws s3 cp deploy-package.zip s3://${{env.S3_BUCKET_NAME}}/$GITHUB_SHA.zip

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{env.S3_BUCKET_NAME}},key=$GITHUB_SHA.zip,bundleType=zip
