name: CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["*"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Disable proxy env
        run: |
          unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy || true

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
        env:
          GRADLE_OPTS: "-Djava.net.useSystemProxies=false"